export interface IPersonnel {
    name: string,
    firstname: string,
    nationality: string,
    gender: string,
    email: string,
    phone: string,
    mobile: string,
    address: string,
    presentation1: string,
    presentation2: string,
    presentation3: string,
    presentation4: string,
    presentation5: string,
    imgUrl: string,
    birthday : string,
    call : string,
    langageIT: string,
    langue: string,
    framework: string,
}
